name: Deploy TOSCA CSAR with Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container: ubuntu:21.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ./01install-xopera.sh
      - name: Validate
        run: opera validate SugarCRM-Interop-20130803.zip
      - name: Deploy
        # run this step even if previous steps failed
        if: ${{ !cancelled() }}
        run: opera deploy SugarCRM-Interop-20130803.zip
      - name: Test
        run: |
          curl -s http://localhost
